Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,6 @@ on: [push]
 
 jobs:
   generate_j2v8_archives:
-    name: Create J2V8 Linux jar and Android aar archive files
     strategy:
       fail-fast: true
       matrix:
@@ -15,6 +14,7 @@ jobs:
             os: ubuntu-latest
 
     runs-on: ${{ matrix.os }}
+    name: Build for ${{ matrix.target }}
 
     steps:
     - name: Checkout
@@ -27,12 +27,15 @@ jobs:
         unzip libv8_8.3.110.9_monolith.zip -d v8.out
 
         # start j2v8 build
-        if [ "${{ matrix.os }}" = "win32" ];
+        if [ "${{ matrix.target }}" = "win32" ];
         then
           python build.py -t win32 -a x64 --docker j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
-        elif [ "${{ matrix.os }}" = "linux" ];
+        elif [ "${{ matrix.target }}" = "linux" ];
         then
           python build.py -t linux -a x64 --docker j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
+        else 
+          echo "Invalid target ${{ matrix.target }}"
+          exit 1
         fi
         #python build.py -t linux -a x64 --docker j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
         #python build.py -t android -a x86 --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
